export const SET_LOCATION_PASS = 'SET_LOCATION_PASS';
export const SET_LOCATION_FAIL = 'SET_LOCATION_FAIL';

export const FETCH_WEATHER_PASS = 'FETCH_WEATHER_PASS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';